race_data = {
    "Melbourne": {
        "round": 1,
        "jolpica_circuit_id": "albert_park",
        "country": "Australia",
        "country_code": "AU",
        "gp_name": "Australian Grand Prix",
        "circuit_name": "Melbourne Grand Prix Circuit",
        "circuit_length_km": 5.303,
        "number_of_laps": 58,
        "race_distance_km": 307.574,
        "number_of_corners": 16,
        "drs_zones": 3,
        "first_grand_prix": 1996,
        "fastest_lap": {"time": "1:20.235", "driver": "Charles Leclerc", "year": 2022},
        "is_sprint": False,
        "f1_url_slug": "australia",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackalbertparkdetailed.png",
    },
    "Shanghai": {
        "round": 2,
        "jolpica_circuit_id": "shanghai",
        "country": "China",
        "country_code": "CN",
        "gp_name": "Chinese Grand Prix",
        "circuit_name": "Shanghai International Circuit",
        "circuit_length_km": 5.451,
        "number_of_laps": 56,
        "race_distance_km": 305.066,
        "number_of_corners": 16,
        "drs_zones": 2,
        "first_grand_prix": 2004,
        "fastest_lap": {"time": "1:32.238", "driver": "Michael Schumacher", "year": 2004},
        "is_sprint": True,
        "f1_url_slug": "china",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackshanghaïdetailed.png",
    },
    "Suzuka": {
        "round": 3,
        "jolpica_circuit_id": "suzuka",
        "country": "Japan",
        "country_code": "JP",
        "gp_name": "Japanese Grand Prix",
        "circuit_name": "Suzuka Circuit",
        "circuit_length_km": 5.807,
        "number_of_laps": 53,
        "race_distance_km": 307.471,
        "number_of_corners": 18,
        "drs_zones": 1,
        "first_grand_prix": 1987,
        "fastest_lap": {"time": "1:30.983", "driver": "Lewis Hamilton", "year": 2019},
        "is_sprint": False,
        "f1_url_slug": "japan",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026tracksuzukadetailed.png",
    },
    "Miami Gardens": {
        "round": 4,
        "jolpica_circuit_id": "miami",
        "country": "United States",
        "country_code": "US",
        "gp_name": "Miami Grand Prix",
        "circuit_name": "Miami International Autodrome",
        "circuit_length_km": 5.412,
        "number_of_laps": 57,
        "race_distance_km": 308.326,
        "number_of_corners": 19,
        "drs_zones": 3,
        "first_grand_prix": 2022,
        "fastest_lap": {"time": "1:29.708", "driver": "Max Verstappen", "year": 2023},
        "is_sprint": True,
        "f1_url_slug": "miami",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmiamidetailed.png",
    },
    "Montréal": {
        "round": 5,
        "jolpica_circuit_id": "villeneuve",
        "country": "Canada",
        "country_code": "CA",
        "gp_name": "Canadian Grand Prix",
        "circuit_name": "Circuit Gilles Villeneuve",
        "circuit_length_km": 4.361,
        "number_of_laps": 70,
        "race_distance_km": 305.27,
        "number_of_corners": 14,
        "drs_zones": 3,
        "first_grand_prix": 1978,
        "fastest_lap": {"time": "1:13.078", "driver": "Valtteri Bottas", "year": 2019},
        "is_sprint": True,
        "f1_url_slug": "canada",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmontrealdetailed.png",
    },
    "Monte Carlo": {
        "round": 6,
        "jolpica_circuit_id": "monaco",
        "country": "Monaco",
        "country_code": "MC",
        "gp_name": "Monaco Grand Prix",
        "circuit_name": "Circuit de Monaco",
        "circuit_length_km": 3.337,
        "number_of_laps": 78,
        "race_distance_km": 260.286,
        "number_of_corners": 19,
        "drs_zones": 1,
        "first_grand_prix": 1950,
        "fastest_lap": {"time": "1:12.909", "driver": "Lando Norris", "year": 2023},
        "is_sprint": False,
        "f1_url_slug": "monaco",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmonacodetailed.png",
    },
    "Barcelona": {
        "round": 7,
        "jolpica_circuit_id": "catalunya",
        "country": "Spain",
        "country_code": "ES",
        "gp_name": "Barcelona-Catalunya Grand Prix",
        "circuit_name": "Circuit de Barcelona-Catalunya",
        "circuit_length_km": 4.655,
        "number_of_laps": 66,
        "race_distance_km": 307.104,
        "number_of_corners": 16,
        "drs_zones": 2,
        "first_grand_prix": 1991,
        "fastest_lap": {"time": "1:18.149", "driver": "Max Verstappen", "year": 2021},
        "is_sprint": False,
        "f1_url_slug": "barcelona",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackbarcelonadetailed.png",
    },
    "Spielberg": {
        "round": 8,
        "jolpica_circuit_id": "red_bull_ring",
        "country": "Austria",
        "country_code": "AT",
        "gp_name": "Austrian Grand Prix",
        "circuit_name": "Red Bull Ring",
        "circuit_length_km": 4.318,
        "number_of_laps": 71,
        "race_distance_km": 306.452,
        "number_of_corners": 10,
        "drs_zones": 3,
        "first_grand_prix": 1970,
        "fastest_lap": {"time": "1:05.619", "driver": "Carlos Sainz", "year": 2020},
        "is_sprint": False,
        "f1_url_slug": "austria",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackspielbegdetailed.png",
    },
    "Silverstone": {
        "round": 9,
        "jolpica_circuit_id": "silverstone",
        "country": "United Kingdom",
        "country_code": "GB",
        "gp_name": "British Grand Prix",
        "circuit_name": "Silverstone Circuit",
        "circuit_length_km": 5.891,
        "number_of_laps": 52,
        "race_distance_km": 306.198,
        "number_of_corners": 18,
        "drs_zones": 2,
        "first_grand_prix": 1950,
        "fastest_lap": {"time": "1:27.097", "driver": "Max Verstappen", "year": 2020},
        "is_sprint": True,
        "f1_url_slug": "great-britain",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026tracksilvestonedetailed.png",
    },
    "Spa-Francorchamps": {
        "round": 10,
        "jolpica_circuit_id": "spa",
        "country": "Belgium",
        "country_code": "BE",
        "gp_name": "Belgian Grand Prix",
        "circuit_name": "Circuit de Spa-Francorchamps",
        "circuit_length_km": 7.004,
        "number_of_laps": 44,
        "race_distance_km": 308.052,
        "number_of_corners": 19,
        "drs_zones": 2,
        "first_grand_prix": 1950,
        "fastest_lap": {"time": "1:41.252", "driver": "Valtteri Bottas", "year": 2018},
        "is_sprint": False,
        "f1_url_slug": "belgium",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackspadetailed.png",
    },
    "Budapest": {
        "round": 11,
        "jolpica_circuit_id": "hungaroring",
        "country": "Hungary",
        "country_code": "HU",
        "gp_name": "Hungarian Grand Prix",
        "circuit_name": "Hungaroring",
        "circuit_length_km": 4.381,
        "number_of_laps": 70,
        "race_distance_km": 306.63,
        "number_of_corners": 14,
        "drs_zones": 1,
        "first_grand_prix": 1986,
        "fastest_lap": {"time": "1:16.627", "driver": "Lewis Hamilton", "year": 2020},
        "is_sprint": False,
        "f1_url_slug": "hungary",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackhungaroringdetailed.png",
    },
    "Zandvoort": {
        "round": 12,
        "jolpica_circuit_id": "zandvoort",
        "country": "Netherlands",
        "country_code": "NL",
        "gp_name": "Dutch Grand Prix",
        "circuit_name": "Circuit Zandvoort",
        "circuit_length_km": 4.259,
        "number_of_laps": 72,
        "race_distance_km": 306.648,
        "number_of_corners": 14,
        "drs_zones": 2,
        "first_grand_prix": 1952,
        "fastest_lap": {"time": "1:11.097", "driver": "Lewis Hamilton", "year": 2021},
        "is_sprint": True,
        "f1_url_slug": "netherlands",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackzandvoortdetailed.png",
    },
    "Monza": {
        "round": 13,
        "jolpica_circuit_id": "monza",
        "country": "Italy",
        "country_code": "IT",
        "gp_name": "Italian Grand Prix",
        "circuit_name": "Autodromo Nazionale di Monza",
        "circuit_length_km": 5.793,
        "number_of_laps": 53,
        "race_distance_km": 306.72,
        "number_of_corners": 11,
        "drs_zones": 2,
        "first_grand_prix": 1950,
        "fastest_lap": {"time": "1:21.046", "driver": "Rubens Barrichello", "year": 2004},
        "is_sprint": False,
        "f1_url_slug": "italy",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmonzadetailed.png",
    },
    "Madrid": {
        "round": 14,
        "jolpica_circuit_id": "madrid",
        "country": "Spain",
        "country_code": "ES",
        "gp_name": "Spanish Grand Prix",
        "circuit_name": "Madring Circuit",
        "circuit_length_km": 5.474,
        "number_of_laps": 57,
        "race_distance_km": 312.018,
        "number_of_corners": 20,
        "drs_zones": 3,
        "first_grand_prix": 2026,
        "fastest_lap": {"time": None, "driver": None, "year": None},
        "is_sprint": False,
        "f1_url_slug": "madrid",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmadriddetailed.png",
    },
    "Baku": {
        "round": 15,
        "jolpica_circuit_id": "baku",
        "country": "Azerbaijan",
        "country_code": "AZ",
        "gp_name": "Azerbaijan Grand Prix",
        "circuit_name": "Baku City Circuit",
        "circuit_length_km": 6.003,
        "number_of_laps": 51,
        "race_distance_km": 306.049,
        "number_of_corners": 20,
        "drs_zones": 2,
        "first_grand_prix": 2017,
        "fastest_lap": {"time": "1:43.009", "driver": "Charles Leclerc", "year": 2019},
        "is_sprint": False,
        "f1_url_slug": "azerbaijan",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackbakudetailed.png",
    },
    "Marina Bay": {
        "round": 16,
        "jolpica_circuit_id": "marina_bay",
        "country": "Singapore",
        "country_code": "SG",
        "gp_name": "Singapore Grand Prix",
        "circuit_name": "Marina Bay Street Circuit",
        "circuit_length_km": 5.063,
        "number_of_laps": 61,
        "race_distance_km": 308.706,
        "number_of_corners": 19,
        "drs_zones": 3,
        "first_grand_prix": 2008,
        "fastest_lap": {"time": "1:35.867", "driver": "Lewis Hamilton", "year": 2023},
        "is_sprint": True,
        "f1_url_slug": "singapore",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmarinabaydetailed.png",
    },
    "Austin": {
        "round": 17,
        "jolpica_circuit_id": "americas",
        "country": "United States",
        "country_code": "US",
        "gp_name": "United States Grand Prix",
        "circuit_name": "Circuit of the Americas",
        "circuit_length_km": 5.513,
        "number_of_laps": 56,
        "race_distance_km": 308.405,
        "number_of_corners": 20,
        "drs_zones": 2,
        "first_grand_prix": 2012,
        "fastest_lap": {"time": "1:36.169", "driver": "Charles Leclerc", "year": 2019},
        "is_sprint": False,
        "f1_url_slug": "united-states",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackcotadetailed.png",
    },
    "Mexico City": {
        "round": 18,
        "jolpica_circuit_id": "rodriguez",
        "country": "Mexico",
        "country_code": "MX",
        "gp_name": "Mexican Grand Prix",
        "circuit_name": "Autodromo Hermanos Rodriguez",
        "circuit_length_km": 4.304,
        "number_of_laps": 71,
        "race_distance_km": 305.354,
        "number_of_corners": 17,
        "drs_zones": 3,
        "first_grand_prix": 1963,
        "fastest_lap": {"time": "1:17.774", "driver": "Valtteri Bottas", "year": 2021},
        "is_sprint": False,
        "f1_url_slug": "mexico",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackmexicocitydetailed.png",
    },
    "São Paulo": {
        "round": 19,
        "jolpica_circuit_id": "interlagos",
        "country": "Brazil",
        "country_code": "BR",
        "gp_name": "Brazilian Grand Prix",
        "circuit_name": "Autodromo Jose Carlos Pace",
        "circuit_length_km": 4.309,
        "number_of_laps": 71,
        "race_distance_km": 305.879,
        "number_of_corners": 15,
        "drs_zones": 2,
        "first_grand_prix": 1973,
        "fastest_lap": {"time": "1:10.540", "driver": "Valtteri Bottas", "year": 2018},
        "is_sprint": False,
        "f1_url_slug": "brazil",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackinterlagosdetailed.png",
    },
    "Las Vegas": {
        "round": 20,
        "jolpica_circuit_id": "vegas",
        "country": "United States",
        "country_code": "US",
        "gp_name": "Las Vegas Grand Prix",
        "circuit_name": "Las Vegas Street Circuit",
        "circuit_length_km": 6.201,
        "number_of_laps": 50,
        "race_distance_km": 310.05,
        "number_of_corners": 17,
        "drs_zones": 3,
        "first_grand_prix": 2023,
        "fastest_lap": {"time": "1:35.490", "driver": "Oscar Piastri", "year": 2024},
        "is_sprint": False,
        "f1_url_slug": "las-vegas",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026tracklasvegas detailed.png",
    },
    "Lusail": {
        "round": 21,
        "jolpica_circuit_id": "losail",
        "country": "Qatar",
        "country_code": "QA",
        "gp_name": "Qatar Grand Prix",
        "circuit_name": "Lusail International Circuit",
        "circuit_length_km": 5.419,
        "number_of_laps": 57,
        "race_distance_km": 308.826,
        "number_of_corners": 16,
        "drs_zones": 2,
        "first_grand_prix": 2021,
        "fastest_lap": {"time": "1:24.319", "driver": "Max Verstappen", "year": 2023},
        "is_sprint": False,
        "f1_url_slug": "qatar",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026tracklusaildetailed.png",
    },
    "Yas Marina": {
        "round": 22,
        "jolpica_circuit_id": "yas_marina",
        "country": "Abu Dhabi",
        "country_code": "AE",
        "gp_name": "Abu Dhabi Grand Prix",
        "circuit_name": "Yas Marina Circuit",
        "circuit_length_km": 5.554,
        "number_of_laps": 55,
        "race_distance_km": 305.355,
        "number_of_corners": 16,
        "drs_zones": 2,
        "first_grand_prix": 2009,
        "fastest_lap": {"time": "1:26.103", "driver": "Max Verstappen", "year": 2021},
        "is_sprint": False,
        "f1_url_slug": "abu-dhabi",
        "picture_url": "https://media.formula1.com/image/upload/c_fit,h_400/q_auto/v1740000001/common/f1/2026/track/2026trackyasmarinadetailed.png",
    },
}